# Build the app image
FROM python:3.10

# Create directory for the app user
RUN mkdir -p /home/app

# Create the app user
RUN groupadd app && useradd -g app app

# Create the home directory
ENV APP_HOME=/home/app/api
RUN mkdir -p $APP_HOME
WORKDIR $APP_HOME

# install
COPY . $APP_HOME
RUN pip install --trusted-host pypi.org --trusted-host files.pythonhosted.org -r requirements-dev.txt
# Como tem o arquivo pyproject.toml (manifesto com tudo que precisa para configurar o projeto, pode usar como exemplo mudando 
# apenas os valores, mas ja tem as dependecias e os arquivos de requeriment q vai usar para instalar e montar todo ambiente necessario
RUN pip install --trusted-host pypi.org --trusted-host files.pythonhosted.org -e .

RUN chown -R app:app $APP_HOME
USER app

CMD ["uvicorn","dundie.app:app","--host=0.0.0.0","--port=8000","--reload"]
